openapi: 3.0.0
info:
  title: API ECO Surv PHP Laravel Exercise
  version: "1.0"
servers:
  - url: http://localhost

paths:

  /breed:
    get:
      description: Get all breeds
      tags:
        - Breed
      responses:
        200:
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Breed'

  /breed/{id}:
    get:
      description: Get breed by id
      tags:
        - Breed
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: Breed id
      responses:
        200:
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Breed'

  /breed/random/:
    get:
      description: Get a random breed
      tags:
        - Breed
      responses:
        200:
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Breed'



  /breed/{id}/image:
    get:
      description: Get image of breed by id
      tags:
        - Breed
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: Breed id
      responses:
        200:
          description: Ok
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary


components:
  schemas:

    Breed:
      type: object
      properties:
        name:
          type: string
          example: breed name

